# Generated by Django 3.2 on 2021-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('year', models.SmallIntegerField(verbose_name='Создано')),
                ('copy_count', models.SmallIntegerField(verbose_name='Издало книг')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_release',
            field=models.SmallIntegerField(verbose_name='Год выхода в печать'),
        ),
    ]
