# Generated by Django 3.2 on 2021-05-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20210509_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='copy_count',
            new_name='book_count',
        ),
    ]
